# Makefile
test: ImageProcessing.cpp 
	g++ -Wall -pthread ImageProcessing.cpp -o test -I/usr/local/include -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_videoio -lopencv_imgproc -lopencv_features2d -lopencv_video -lopencv_calib3d -lpigpio -lrt
